name: artifacts-implementaion

on:
    push: 


jobs:
    uploading-current-users-file:
        name: "Get the Runner users"
        runs-on: windows-latest
        steps:
            - run: | # Create the file
                pwd
                get-netipconfiguration > users.txt

            - uses: actions/upload-artifact@v2 # upload the created file
              with:
                name: users
                path: users.txt
                retention-days: 10
    
    downloading-current-users-file:
        name: "Download the current users file"
        runs-on: windows-latest
        needs: uploading-current-users-file
        steps:
            - run: pwd
            - uses: actions/download-artifact@v2
              with:
                name: users
            - name: Printing Users
              run: cat users.txt

