name: 'Custom Env Vars'

on:
  workflow_dispatch:
  
env:
  Day: "a Vications"
  

jobs: 
  mainjob:
    name: 'Print the env vars'
    runs-on: ubuntu-latest

    env:
      Greeting: Dear
    
    steps:
    - name: print-values-of-env-vars
      run: |
        echo "${{env.Greeting}} Nawaf"
