name: "get-caller-identity"

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1


permissions:
    id-token: write
    contents: read


jobs:
  get-caller-identity:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Creds"
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
            aws-region: ${{env.AWS_REGION}}
            role-to-assume: "arn:aws:iam::215534817852:role/Github-OIDC"
            role-session-name: samplerolesession
      - name: "GET-CALLER-IDENTITY"
        run: |
          aws sts get-caller-identity

