name: "secret-workflow"

on:
    workflow_dispatch: 
env:
    secret-value: ${{secrets.MY_AWS_PASS}}


jobs:
    getting-my-secret-job:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Here is my Secret Come and get it ${{env.secret-value}}"