name: "secret-workflow"

on:
    workflow_dispatch: 


jobs:
    getting-my-secret-job:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Here is my Secret Come and get it $APP_SECRET"
              env:
                APP_SECRET: ${{secrets.MY_AWS_PASS}}