name: self-hosted-runner

on:
    workflow_dispatch

jobs:
    test-linux-job:
        name: "Test Runner"
        runs-on: [self-hosted, Windows, x64, PsGeek]
        steps:
            - name: "Run uname"
              run: |
               echo "Habibi iam PS i don't know uname"