name: "TEST JWT"

on:
    workflow_dispatch

jobs:
  inspect-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Request OIDC token
        id: oidc
        run: |
          TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          echo "::add-mask::$TOKEN"
          echo $TOKEN | jq '.' > token.json
      - name: Decode token
        run: |
          cat token.json | jq -r '.value' | cut -d "." -f2 | base64 -d | jq '.'
